name: Deploy to Cloudflare Pages

on: 
  push:
    paths:
      - "src/**"
      - "public/**"
      - ".github/workflows/publish.yml"
    branches: [main]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install, build, and upload your site output
        uses: withastro/action@v2
        with:
          package-manager: pnpm@latest
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{secrets.CLOUDFLARE_ACCOUNT_ID}}
          projectName: muproknowledge
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
